### PR TITLE
Frontend Decibel Calls Task

### PR DESCRIPTION
**Pull request by zainabazeemTT**
Screenshot 2023-07-25 at 3 25 53 PM

Please follow this PR template.

@zainabazeemTT

### CODE REVIEW

**Comment by asadrazaatx** [comment]
@zainabazeemTT I've changed the commit message, please follow directions.

**Comment by zainabazeemTT** [comment]
## Description
## Type of change
Please delete options that are not relevant.
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
## How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.
- [x] Test A
## Checklist:
- [x] I have performed a self-review of my own code
- [x] I have tested my code to prove my fix is effective or that my feature works
- [ ] I have commented my code in areas where it's hard to make the code speak for itself
- [x] My changes breaks no tests

**Comment by zainabazeemTT** [comment]
## Description
I've completed integrating the APIs and have tested the functionality for each as well. I have edited and utilized the dashboard-3 and sign-in pages that were already present in the repository: https://github.com/Decibel-io/decibel-next-app.  I've formatted the columns in the table that required a badge/chip component so they are categorized prominently. Phone numbers are now also formatted using E164 standard. 
## Fixes # (issue)
1 - Added tags for column 1 and column 2 in in table. 
2 - Used react-phone-number-input and libphonenumber-js for formatting phone numbers in table.
3 - Changed color codes in libs/theme/color.ts file.
4 - Replaced if-else blocks with ternary operators/switch statement.
## Type of change
Please delete options that are not relevant
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
## How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.
- [x] Test A : Tested all format changes by rendering on the UI. 

Before changes: 

Screenshot (222)

After changes: 

Screenshot (252)

## Checklist:
- [x] I have performed a self-review of my own code
- [x] I have tested my code to prove my fix is effective or that my feature works
- [x] I have commented my code in areas where it's hard to make the code speak for itself
- [x] My changes breaks no tests
## Build is Passing:
Please attach screenshot of successful build.
Screenshot 2023-07-26 172827

## Paste Loom videos or Product walkthrough
- [x] - my loom video link : https://www.loom.com/share/6de8c1e6321f430da1c612b1a8a14100?sid=2eb42c82-7b11-4aa4-b977-3c89543d0ef6

**Comment by zainabazeemTT** [comment]
@asadrazaatx I've updated the PR thread following the syntax in PR template. Let me know if there are any additions to be made.

**Pull request closed without merging**
